language: android

android:
  components:
    - build-tools-19.0.3

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew clean
  - ./gradlew build
